options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logStreamingOption: STREAM_ON

logsBucket: "gs://budhgaya-cloud-build-logs"

timeout: "1200s"

substitutions:
  # Default placeholders for custom substitutions. These will be overridden by CLI --substitutions.
  # temporary default short sha for manual submits; override via --substitutions if needed
  _SHORT_SHA: "2a111f2"
  _REGION: "europe-west1"
  _SERVICE: "budhgaya-com"
  _IMAGE: "budhgaya-client"

steps:
  - id: "Build-app"
    name: "node:18"
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        cd client
        # Always use npm install with legacy peer deps to avoid peer resolution issues
        npm install --legacy-peer-deps --prefer-offline --no-audit --no-fund
        npm run build

  # Build the Docker image (tagged with the project registry and short sha)
  - id: "Build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_IMAGE}:${_SHORT_SHA}
      - client

  - id: "Push-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/${_IMAGE}:${_SHORT_SHA}

  - id: "Deploy-to-Cloud-Run"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        echo "Deploying to Cloud Run service: ${_SERVICE} (region: ${_REGION})"
        gcloud run deploy "${_SERVICE}" --image gcr.io/$PROJECT_ID/${_IMAGE}:${_SHORT_SHA} --region "${_REGION}" --platform managed --allow-unauthenticated

  # Note: we split build/push and deploy into separate steps so each runs
  # with the appropriate builder image (docker/gcloud) and avoid missing
  # binaries inside the wrong image.

# images: intentionally omitted

# availableSecrets example (uncomment and configure if required)
# availableSecrets:
#   secretManager:
#     - versionName: "projects/PROJECT_ID/secrets/openai-api-key/versions/latest"
#       env: "OPENAI_API_KEY"
