options:
  logging: CLOUD_LOGGING_ONLY
  timeout: "1200s"

substitutions:
  # custom substitutions expected: _SHORT_SHA, _REGION, _SERVICE, _IMAGE

steps:
  - id: "Build-app"
    name: "node:18"
    entrypoint: bash
    args:
      - -lc
      - |
        set -e
        cd client
        npm ci --prefer-offline --no-audit --no-fund
        npm run build

  - id: "Build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/${PROJECT_ID}/${_IMAGE}:${_SHORT_SHA}"
      - client

  - id: "Push-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/${PROJECT_ID}/${_IMAGE}:${_SHORT_SHA}"

  - id: "Deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE}"
      - --image
      - "gcr.io/${PROJECT_ID}/${_IMAGE}:${_SHORT_SHA}"
      - --region
      - "${_REGION}"
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - "gcr.io/${PROJECT_ID}/${_IMAGE}:${_SHORT_SHA}"

# availableSecrets example (uncomment and configure if required)
# availableSecrets:
#   secretManager:
#     - versionName: "projects/PROJECT_ID/secrets/openai-api-key/versions/latest"
#       env: "OPENAI_API_KEY"
node_modules
npm-debug.log
.git
.gitignore
client/node_modules
client/.env
build
dist