options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/budhgaya-client:${_SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/budhgaya-client:${_SHORT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - 'budhgaya-client'
      - --image
      - 'gcr.io/${PROJECT_ID}/budhgaya-client:${_SHORT_SHA}'
      - --region
      - 'us-central1'
      - --platform
      - managed
      - --allow-unauthenticated
images:
  - 'gcr.io/${PROJECT_ID}/budhgaya-client:${_SHORT_SHA}'
