// Simple Express server to serve the React app built into `server/build`
// Load environment variables from .env file if it exists (for local development)
try {
	require('dotenv').config();
} catch (err) {
	// dotenv package may not be installed in some environments
}

const express = require('express');
const path = require('path');
const fs = require('fs');

const app = express();
// Compression for responses
try {
	const compression = require('compression');
	app.use(compression());
} catch (err) {
	// compression package may not be installed in some environments
}
app.use(express.json());
const PORT = process.env.PORT || 8080;

// optional background scheduler for scraping
try { require('./scheduler'); } catch (_) {}

// Serve static files from the `build` folder generated by the client build
const buildPath = path.join(__dirname, 'build');
// Cache static assets aggressively; index.html should not be cached long-term
app.use((req, res, next) => {
	if (req.url.startsWith('/static/') || req.url.match(/\.(js|css|png|jpg|jpeg|webp|svg)$/)) {
		res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
	}
	next();
});
app.use(express.static(buildPath));

// Health endpoint for Cloud Run / health checks
app.get('/health', (req, res) => res.status(200).send('OK'));

// API routes
app.use('/api', require('./routes/community'));
app.use('/api', require('./routes/contact'));
app.use('/api', require('./routes/chat'));
app.use('/api', require('./routes/encyclopedia'));
app.use('/api', require('./routes/subscribe'));

// All remaining requests return the React app, so client-side routing works
app.get('*', (req, res) => {
	const indexFile = path.join(buildPath, 'index.html');
	if (!fs.existsSync(indexFile)) {
		return res.status(500).send('Client build not found.');
	}
	res.sendFile(indexFile);
});

// Start server and bind to 0.0.0.0 so Cloud Run can reach it
const LISTEN_HOST = process.env.LISTEN_HOST || '0.0.0.0';
app.listen(PORT, LISTEN_HOST, () => {
  // Server started
});